# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-COBSCComp182P-021' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-COBSCComp182P-021
    pod 'Firebase/Auth'
    pod 'Firebase/Analytics'   
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'

end
